package com.harshana.wposandroiposapp.DevArea;


import com.harshana.wposandroiposapp.Base.ErrData;

/**
 * Created by harshana_m on 10/25/2018.
 */

public class ErrorInfoDev extends ErrData {
    private static ErrorInfoDev myInstance = null;

    public static ErrorInfoDev getMyInstance() {
        if (myInstance == null)
            return new ErrorInfoDev();

        return myInstance;
    }

    public void initErrorData() {
        addErrorCodeWithDesc(1  ,"Please Call"                                 );
        addErrorCodeWithDesc(2  ,"Referral"                                    );
        addErrorCodeWithDesc(3  ,"Error, Call Help"                            );
        addErrorCodeWithDesc(4  ,"Please, Pick Up Card"                           );
        addErrorCodeWithDesc(5  ,"Do Not Honor"                               );
        addErrorCodeWithDesc(6  ,"Error"                                       );
        addErrorCodeWithDesc(7  ,"Pickup Card, Spl Cond"                       );
        addErrorCodeWithDesc(8  ,"Verify ID and Sign"                          );
        addErrorCodeWithDesc(9  ,"Accepted"                                    );
        addErrorCodeWithDesc(10 ,"Approved for partial amount"                       );
        addErrorCodeWithDesc(11 ,"Approved (VIP)"                              );
        addErrorCodeWithDesc(12 ,"Error , Call Help"                            );
        addErrorCodeWithDesc(13 ,"Error , Invalid Amount"                         );
        addErrorCodeWithDesc(14 ,"ERROR - INVALID CARD"                        );
        addErrorCodeWithDesc(15 ,"No such Issuer"                              );
        addErrorCodeWithDesc(16 ,"Approved, Update Tk 3"                       );
        addErrorCodeWithDesc(17 ,"Customer Cancellation"                       );
        addErrorCodeWithDesc(18 ,"Customer Dispute"                            );
        addErrorCodeWithDesc(19 ,"RE-ENTER TRANSACTION"                        );
        addErrorCodeWithDesc(20 ,"Invalid Response"                            );
        addErrorCodeWithDesc(21 ,"NO TRANSACTIONS"                             );
        addErrorCodeWithDesc(22 ,"Suspected Malfunction"                       );
        addErrorCodeWithDesc(23 ,"Unaccepted Trans Fee"                        );
        addErrorCodeWithDesc(24 ,"File Upd not Suported"                       );
        addErrorCodeWithDesc(25 ,"ERROR-TERM. INACTIVE"                        );
        addErrorCodeWithDesc(26 ,"Dup Rec,Old Rec Rplcd"                       );
        addErrorCodeWithDesc(27 ,"Field Edit Error"                            );
        addErrorCodeWithDesc(28 ,"File Locked out"                             );
        addErrorCodeWithDesc(29 ,"File Update Error"                           );
        addErrorCodeWithDesc(30 ,"ERROR - INVLD FORMAT"                        );
        addErrorCodeWithDesc(31 ,"ERROR - NS"                                  );
        addErrorCodeWithDesc(32 ,"Completed Partially"                         );
        addErrorCodeWithDesc(33 ,"Expired Card"                                );
        addErrorCodeWithDesc(34 ,"Suspected Fraud"                             );
        addErrorCodeWithDesc(35 ,"Contact Acquirer"                            );
        addErrorCodeWithDesc(36 ,"Restricted Card"                             );
        addErrorCodeWithDesc(37 ,"Call Acq. Security"                          );
        addErrorCodeWithDesc(38 ,"PIN tries Exceeded"                          );
        addErrorCodeWithDesc(39 ,"No Credit Account"                           );
        addErrorCodeWithDesc(40 ,"Func. not Supported"                         );
        addErrorCodeWithDesc(41 ,"PLEASE CALL - LC"                            );
        addErrorCodeWithDesc(42 ,"No Universal Account"                        );
        addErrorCodeWithDesc(43 ,"PLEASE CALL - SC"                            );
        addErrorCodeWithDesc(44 ,"No Investment Account"                       );
        addErrorCodeWithDesc(45 ,"ISO error #45"                               );
        addErrorCodeWithDesc(46 ,"ISO error #46"                               );
        addErrorCodeWithDesc(47 ,"ISO error #47"                               );
        addErrorCodeWithDesc(48 ,"Refer to issuer"                             );
        addErrorCodeWithDesc(49 ,"ISO error #49"                               );
        addErrorCodeWithDesc(50 ,"ISO error #50"                               );
        addErrorCodeWithDesc(51 ,"DECLINED"                                    );
        addErrorCodeWithDesc(52 ,"No Checking Account"                         );
        addErrorCodeWithDesc(53 ,"No Savings Account"                          );
        addErrorCodeWithDesc(54 ,"EXPIRED CARD"                                );
        addErrorCodeWithDesc(55 ,"Incorrect PIN"                               );
        addErrorCodeWithDesc(56 ,"No Card Record"                              );
        addErrorCodeWithDesc(57 ,"Txn not Permtd-card"                         );
        addErrorCodeWithDesc(58 ,"INVALID TRANSACTION"                         );
        addErrorCodeWithDesc(59 ,"Suspected Fraud"                             );
        addErrorCodeWithDesc(60 ,"Contact Acquirer"                            );
        addErrorCodeWithDesc(61 ,"Exceeds Amount Limit"                        );
        addErrorCodeWithDesc(62 ,"Restricted Card"                             );
        addErrorCodeWithDesc(63 ,"Security Violation"                          );
        addErrorCodeWithDesc(64 ,"Org Amount Incorrect"                        );
        addErrorCodeWithDesc(65 ,"Freq. Limit Exceed"                          );
        addErrorCodeWithDesc(66 ,"Call Acq's Security"                         );
        addErrorCodeWithDesc(67 ,"Hard Capture"                                );
        addErrorCodeWithDesc(68 ,"Resp Recvd too Late"                         );
        addErrorCodeWithDesc(69 ,"ISO error #69 "                              );
        addErrorCodeWithDesc(70 ,"ISO error #70 "                              );
        addErrorCodeWithDesc(71 ,"ISO error #71 "                              );
        addErrorCodeWithDesc(72 ,"ISO error #72 "                              );
        addErrorCodeWithDesc(73 ,"ISO error #73 "                              );
        addErrorCodeWithDesc(74 ,"ISO error #74 "                              );
        addErrorCodeWithDesc(75 ,"Pin Tries Exceeded"                          );
        addErrorCodeWithDesc(76 ,"ERROR - DESCRIPTOR"                          );
        addErrorCodeWithDesc(77 ,"RECONCILE ERROR"                             );
        addErrorCodeWithDesc(78 ,"OLD ROC NOT FOUND"                           );
        addErrorCodeWithDesc(79 ,"BATCH ALREADY OPEN"                          );
        addErrorCodeWithDesc(80 ,"BAD BATCH NUMBER"                            );
        addErrorCodeWithDesc(81 ,"Private error #81"                           );
        addErrorCodeWithDesc(82 ,"Private error #82"                           );
        addErrorCodeWithDesc(83 ,"Private error #83"                           );
        addErrorCodeWithDesc(84 ,"Private error #84"                           );
        addErrorCodeWithDesc(85 ,"BATCH NOT FOUND"                             );
        addErrorCodeWithDesc(86 ,"Private error #86"                           );
        addErrorCodeWithDesc(87 ,"Private error #87"                           );
        addErrorCodeWithDesc(88 ,"HAVE CM CALL AMEX"                           );
        addErrorCodeWithDesc(89 ,"BAD TERMINAL ID"                             );
        addErrorCodeWithDesc(90 ,"Cutoff in Process"                           );
        addErrorCodeWithDesc(91 ,"ISSUER UNAVAILABLE"                          );
        addErrorCodeWithDesc(92 ,"Trans can't be Routed"                       );
        addErrorCodeWithDesc(93 ,"Txn cant be Completed"                       );
        addErrorCodeWithDesc(94 ,"ERROR - SEQUENCE NO"                         );
        addErrorCodeWithDesc(95 ,"RECONCILE ERROR"                             );
        addErrorCodeWithDesc(96 ,"ERROR -INVALID message"                          );
        addErrorCodeWithDesc(97 ,"INVALID TENURE"                              );
        addErrorCodeWithDesc(98 ,"Resvd. for Nat. use"                         );
        addErrorCodeWithDesc(99 ,"Resvd. for Nat. use"                         );
        addErrorCodeWithDesc(100, "Surcharge amt not Permited on Visa cards"   );
        addErrorCodeWithDesc(101, "Force STIP"                                 );
        addErrorCodeWithDesc(102, "Cash Service Not Available"                 );
        addErrorCodeWithDesc(103, "Cashback rqst exceed issuer limit"          );
        addErrorCodeWithDesc(104, "Decline for CVV2 failure"                   );
        addErrorCodeWithDesc(105, "Invalid biller information"                 );
        addErrorCodeWithDesc(106, "PIN Change"                                 );
        addErrorCodeWithDesc(108, "Stop Payment Order"                         );
        addErrorCodeWithDesc(109, "Revocation of Authorization Order"          );
        addErrorCodeWithDesc(110, "Revocation of All Authorization Order"      );
        addErrorCodeWithDesc(111, "Unable to go online"                        );
        addErrorCodeWithDesc(112, "Forward to issuer"                          );
        addErrorCodeWithDesc(113, "Forward to issuer"                          );
        addErrorCodeWithDesc(114, "DECLINED"                                   );
        addErrorCodeWithDesc(115, "DECLINED"                                   );
        addErrorCodeWithDesc(116, "ISO error"                                  );
        addErrorCodeWithDesc(117, "ISO error"                                  );
        addErrorCodeWithDesc(118, "ISO error"                                  );
        addErrorCodeWithDesc(119, "ISO error"                                  );
        addErrorCodeWithDesc(120, "ISO error"                                  );
        addErrorCodeWithDesc(121, "ISO error"                                  );
        addErrorCodeWithDesc(122, "ISO error"                                  );
        addErrorCodeWithDesc(123, "ISO error"                                  );
        addErrorCodeWithDesc(124, "ISO error"                                  );
        addErrorCodeWithDesc(125, "ISO error"                                  );
        addErrorCodeWithDesc(126, "ISO error"                                  );
        addErrorCodeWithDesc(127, "ISO error"                                  );
        addErrorCodeWithDesc(128, "ISO error"                                  );
        addErrorCodeWithDesc(129, "ISO error"                                  );
        addErrorCodeWithDesc(130, "ISO error"                                  );
        addErrorCodeWithDesc(131, "ISO error"                                  );
        addErrorCodeWithDesc(132, "ISO error"                                  );
        addErrorCodeWithDesc(133, "ISO error"                                  );
        addErrorCodeWithDesc(134, "ISO error"                                  );
        addErrorCodeWithDesc(135, "ISO error"                                  );
        addErrorCodeWithDesc(136, "ISO error"                                  );
        addErrorCodeWithDesc(137, "ISO error"                                  );
        addErrorCodeWithDesc(138, "ISO error"                                  );
        addErrorCodeWithDesc(139, "ISO error"                                  );
        addErrorCodeWithDesc(140, "ISO error"                                  );
        addErrorCodeWithDesc(141, "ISO error"                                  );
        addErrorCodeWithDesc(142, "ISO error"                                  );
        addErrorCodeWithDesc(143, "ISO error"                                  );
        addErrorCodeWithDesc(144, "ISO error"                                  );
        addErrorCodeWithDesc(145, "ISO error"                                  );
        addErrorCodeWithDesc(146, "ISO error"                                  );
        addErrorCodeWithDesc(147, "ISO error"                                  );
        addErrorCodeWithDesc(148, "ISO error"                                  );
        addErrorCodeWithDesc(149, "ISO error"                                  );
        addErrorCodeWithDesc(150, "Channel not found"                          );
        addErrorCodeWithDesc(151, "Invalid terminal"                           );
        addErrorCodeWithDesc(152, "Inactive terminal"                          );
        addErrorCodeWithDesc(153, "Routing not allowed"                        );
        addErrorCodeWithDesc(154, "Requires encpt level should be fully"       );
        addErrorCodeWithDesc(155, "Requires encpt level should be Mac only"    );
        addErrorCodeWithDesc(156, "Requires encryption level should be clear"  );
        addErrorCodeWithDesc(157, "Incorrect key check value"                  );
        addErrorCodeWithDesc(158, "Incorrect officer PIN"                      );
        addErrorCodeWithDesc(159, "Incorrect key id"                           );
        addErrorCodeWithDesc(160, "Incorrect TLE header length"                );
        addErrorCodeWithDesc(161, "Not found TLE header details from request"  );
        addErrorCodeWithDesc(162, "Routing disabled by TLE administrator"      );
        addErrorCodeWithDesc(163, "Requesting algorithm not enabled"           );
        addErrorCodeWithDesc(164, "Invalid encryption level"                   );
        addErrorCodeWithDesc(165, "Request mac alg no enble"                   );
        addErrorCodeWithDesc(166, "Mapping NII not found"                      );
        addErrorCodeWithDesc(167, "NII group not found"                        );
        addErrorCodeWithDesc(168, "MAC failed"                                 );
        addErrorCodeWithDesc(169, "Channel error"                              );
        addErrorCodeWithDesc(170, "Requesting NII not registered"              );
        addErrorCodeWithDesc(171, "Invalid data in request"                    );
        addErrorCodeWithDesc(172, "Requesting key size not enabled"            );
        addErrorCodeWithDesc(173, "Invalid card holder"                        );
        addErrorCodeWithDesc(174, "Inactive card holder"                       );
        addErrorCodeWithDesc(175, "PIN tries exceed"                           );
        addErrorCodeWithDesc(176, "Key downloading Limit exceed"               );
        addErrorCodeWithDesc(177, "Need on-line PIN  verification"             );
        addErrorCodeWithDesc(178, "Need off-line PIN verification"             );
        addErrorCodeWithDesc(209,	"Incorrect key id									"  );
        addErrorCodeWithDesc(210,	"Incorrect TLE header length                        "  );
        addErrorCodeWithDesc(211,	"Not found TLE header details from request          "  );
        addErrorCodeWithDesc(212,	"Routing disabled by TLE administrator              "  );
        addErrorCodeWithDesc(213,	"Requesting algorithm not enabled                   "  );
        addErrorCodeWithDesc(214,	"Invalid encryption level                           "  );
        addErrorCodeWithDesc(215,	"Requesting mac algorithm not enabled               "  );
        addErrorCodeWithDesc(216,	"Mapping NII not found                              "  );
        addErrorCodeWithDesc(217,	"NII group not found                                "  );
        addErrorCodeWithDesc(225,	"MAC failed                                         "  );
        addErrorCodeWithDesc(226,	"Channel error                                      "  );
        addErrorCodeWithDesc(227,	"Requesting NII not registered                      "  );
        addErrorCodeWithDesc(228,	"Invalid data in request                            "  );
        addErrorCodeWithDesc(229,	"Requesting key size not enabled                    "  );
        addErrorCodeWithDesc(230,	"Invalid card holder                                "  );
        addErrorCodeWithDesc(231,	"Inactive card holder                               "  );
        addErrorCodeWithDesc(232,	"PIN tries exceed                                   "  );
        addErrorCodeWithDesc(233,	"Key downloading exceed                             "  );
        addErrorCodeWithDesc(193,	"Channel not found                                  "  );
        addErrorCodeWithDesc(194,	"Invalid terminal                                   "  );
        addErrorCodeWithDesc(195,	"Inactive terminal                                  "  );
        addErrorCodeWithDesc(196,	"Routing not allowed                                "  );
        addErrorCodeWithDesc(197,	"Requires encryption level should be fully          "  );
        addErrorCodeWithDesc(198,	"Requires encryption level should be Mac only       "  );
        addErrorCodeWithDesc(199,	"Requires encryption level should be clear          "  );
        addErrorCodeWithDesc(200,	"Incorrect key check value                          "  );
        addErrorCodeWithDesc(201,	"Incorrect officer PIN                              "  );
    }
}
